spring:
  datasource:
    url: jdbc:mariadb://ip:port/database
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com.github.raphael008.mapper: trace

path:
  image: